### ISSUE TITLE
Task 3: Database Schema

### ISSUE THREAD

**Issue by Shhmabbey** [ratan-ml/Amuhzaan#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details (primary and foreign keys, not null, indexed, unique)
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] table names, column names, and foreign keys are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded

**Comment by Shhmabbey** [comment]
- [ ] Add a constrain to the rating column in the reviews table to make the range 1-5
- [ ] Remove the belongs to association with the cart
- [ ] Add a new table called cart_items that is a joins table between the user and the product, be sure to include a quantity column in this table.
- [ ] Remove the cart table

Basically your cart items will act as your cart and will be a list of all of the items in a cart for a user.

**Comment by raymondtan676** [comment]
Schema has been updated to reflect the change from carts to cart items table. In addition, validation constraints have been included.
